### PR TITLE
HC bump 156

### PR DESCRIPTION
**Pull request by weswalla**
There are a whole bunch of trait bound error:

```
error[E0271]: type mismatch resolving `<EN as std::convert::TryFrom<AvailableCapability>>::Error == std::convert::Infallible`
   --> lib/hdk_semantic_indexes/client/src/lib.rs:476:8
    |
444 | fn request_sync_remote_index<EN, A, B, I, LT, E, E2>(
    |                                               - this type parameter
...
476 |     Ok(call_zome_method::<EN, _, _, _, _, _, _, _>(
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::convert::Infallible`, found type parameter `E`
    |
    = note:        expected enum `std::convert::Infallible`
            found type parameter `E`
note: required by a bound in `call_zome_method`
   --> /Users/weswalla/sprillow/hREA/lib/hdk_records/src/rpc_helpers.rs:37:42
    |
37  |         EN: TryFrom<AvailableCapability, Error = E>,
    |                                          ^^^^^^^^^ required by this bound in `call_zome_method`
```

### CODE REVIEW

**Review by Connoropolous — CHANGES_REQUESTED** [review]
Actually @weswalla you had the right versions before the latest commit. Can we revert that commit? We will have to take a different approach to pinning the HDK dependency. Was it leaking in from dna-auth-resolver because of the HDK dependency being set to "0.0" there? I expect so.

**Comment by weswalla** [comment]
@Connoropolous 
> Was it leaking in from dna-auth-resolver because of the HDK dependency being set to "0.0" there? I expect so.

Yes, exactly.

**Comment by Connoropolous** [comment]
I will propose to Pospi that we specify the dep version over in dna-auth-resolver. This issue occurs regularly

**Comment by weswalla** [comment]
@Connoropolous @pospi 
I forked dna-auth-resolver (https://github.com/weswalla/dna-auth-resolver) as a temp fix to see if it will compile, which is does.

**Comment by Connoropolous** [comment]
for details on they 'why chrono' thing, see this commit: 
https://github.com/holochain/holochain/pull/1527/files

weirdly, you have to "disable" the wasm-bindgen feature by disabling all default features and then only enabling the ones that aren't bindgen. 
bindgen messes with the wasm in ways that breaks the holochain host/guest WASM interface

**Comment by Connoropolous** [comment]
we can now run the integration tests

**Review by Connoropolous — APPROVED** [review]
bingo. 
luckily the tryorama update just got finished today. I didn't even realize till today that we'd be blocked on it.

**Pull request merged**
