### PR TITLE
change is_registered_agent to is_registered

### PR DESCRIPTION
**Pull request by Connoropolous**
note, I didn't take the time yet to test this, but by all appearances this would be more correct than what's there now, based on https://github.com/holochain-open-dev/agent-registration/search?q=is_registered

### CODE REVIEW

**Comment by pospi** [comment]
Nice find, thanks! While we're here- would you like to add yourself to `CONTRIBUTORS.txt`? :slightly_smiling_face:

**Comment by Connoropolous** [comment]
Yeah, I can do that :)

**Comment by Connoropolous** [comment]
there we go @pospi

**Comment by Connoropolous** [comment]
waiting on anything else for this @pospi ?

**Comment by pospi** [comment]
My bad! Just hadn't been paying attention & kinda thought I already merged it :sheep:

**Pull request merged**
