### PR TITLE
Feature/379 vf graphql update

### PR DESCRIPTION
**Pull request by pospi**
Quick updates to GraphQL layer to obviate some current workarounds in other projects. Tested locally and working in the GraphQL Explorer, so will merge & publish this as soon as confirmed the tests are passing.

### CODE REVIEW

**Review by Connoropolous — APPROVED** [review]
seems fine to me 👍

**Comment by Connoropolous** [comment]
nix will run faster on future runs after it caches a bunch of new stuff

**Comment by Connoropolous** [comment]
I think it only failed cause of the 100 minute timeout. Rerunning it it would prbly pass

**Comment by pospi** [comment]
Close enough, I tested the `EconomicResource` math before pushing and that's the only major piece of functionality these changes may impact, other than general "does it compile"&mdash;ness.

**Pull request merged**
