### PR TITLE
More flexible index macros to allow String-based identifiers for agent_type

### LINKED ISSUE #330: read all units query failing to resolve
calling `read_all_units` after 2 units have been created returns the following error:
```
12:32:42 [Tryorama - Local Conductor] debug: Jul 05 12:32:42.149 ERROR wasm_trace: hc_zome_rea_unit::__get_unit_extern:zomes/rea_unit/zome/src/lib.rs:46 output_type = "core::result::Result<hc_zome_rea_unit_rpc::ResponseData, holochain_wasmer_common::result::WasmError>"; bytes = [129, 167, 97, 100, 100, 114, 101, 115, 115, 146, 196, 39, 132, 45, 36, 190, 119, 116, 103, 117, 249, 48, 150, 239, 14, 152, 31, 49, 165, 118, 13, 56, 153, 204, 159, 34, 162, 33, 207, 44, 233, 33, 10, 141, 99, 89, 237, 64, 160, 219, 5, 196, 39, 132, 33, 36, 159, 23, 169, 177, 203, 189, 125, 252, 120, 149, 241, 239, 150, 144, 239, 239, 37, 99, 219, 138, 78, 214, 61, 71, 133, 32, 74, 137, 241, 104, 125, 115, 82, 168, 31, 246]; Deserialize("missing field `id`")

[result]:  {
  page_info: {
    startCursor: '0',
    endCursor: '0',
    hasPreviousPage: true,
    hasNextPage: true
  },
  edges: [],
  errors: [
    {
      Guest: 'Error in remote call Host("Wasm error while working with Ribosome: Deserialize([129, 167, 97, 100, 100, 114, 101, 115, 115, 146, 196, 39, 132, 45, 36, 190, 119, 116, 103, 117, 249, 48, 150, 239, 14, 152, 31, 49, 165, 118, 13, 56, 153, 204, 159, 34, 162, 33, 207, 44, 233, 33, 10, 141, 99, 89, 237, 64, 160, 219, 5, 196, 39, 132, 33, 36, 125, 86, 237, 154, 208, 77, 226, 3, 68, 48, 1, 159, 0, 186, 192, 87, 213, 48, 233, 237, 138, 100, 13, 17, 88, 79, 134, 171, 32, 216, 87, 13, 165, 103, 222, 174])")'
    },
    {
      Guest: 'Error in remote call Host("Wasm error while working with Ribosome: Deserialize([129, 167, 97, 100, 100, 114, 101, 115, 115, 146, 196, 39, 132, 45, 36, 190, 119, 116, 103, 117, 249, 48, 150, 239, 14, 152, 31, 49, 165, 118, 13, 56, 153, 204, 159, 34, 162, 33, 207, 44, 233, 33, 10, 141, 99, 89, 237, 64, 160, 219, 5, 196, 39, 132, 33, 36, 159, 23, 169, 177, 203, 189, 125, 252, 120, 149, 241, 239, 150, 144, 239, 239, 37, 99, 219, 138, 78, 214, 61, 71, 133, 32, 74, 137, 241, 104, 125, 115, 82, 168, 31, 246])")'
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by pospi**
This should help with #326. All `Agent` tests seem to be passing, but I haven't checked the status of them to see which parts of the behaviour they're exercising. Merge when you feel happy with this approach.

Now closes #330 in addition to enabling `agent_type` to work.

### CODE REVIEW

**Review by Connoropolous — CHANGES_REQUESTED** [review]
Looks close!

For me, when I run this:
I get errors on the tests for `people` and `organizations`
not ok 19 query for all people OK
not ok 20 TypeError: Cannot read properties of undefined (reading 'node')
I see these in the logs:
```
11:42:09 [Tryorama - Local Conductor] debug: Jul 07 11:42:09.325 ERROR wasm_trace: hc_zome_rea_agent_index_agent::___internal_index_agent_agent_type_extern:zomes/rea_agent/zome_idx_agent/src/lib.rs:24 output_type = "core::result::Result<hdk_semantic_indexes_zome_rpc::RemoteEntryLinkResponse, holochain_wasmer_common::result::WasmError>"; bytes = [131, 172, 114, 101, 109, 111, 116, 101, 95, 101, 110, 116, 114, 121, 146, 196, 39, 132, 45, 36, 165, 79, 24, 69, 217, 175, 141, 113, 44, 168, 250, 251, 81, 126, 193, 104, 100, 34, 35, 111, 182, 71, 33, 99, 14, 80, 238, 191, 184, 209, 41, 174, 110, 124, 17, 238, 196, 39, 132, 33, 36, 17, 2, 67, 24, 128, 23, 194, 138, 161, 85, 167, 157, 219, 12, 75, 87, 39, 66, 172, 33, 22, 41, 83, 132, 215, 235, 12, 218, 173, 215, 135, 123, 94, 101, 230, 51, 174, 116, 97, 114, 103, 101, 116, 95, 101, 110, 116, 114, 105, 101, 115, 145, 146, 196, 39, 132, 45, 36, 165, 79, 24, 69, 217, 175, 141, 113, 44, 168, 250, 251, 81, 126, 193, 104, 100, 34, 35, 111, 182, 71, 33, 99, 14, 80, 238, 191, 184, 209, 41, 174, 110, 124, 17, 238, 196, 39, 132, 33, 36, 215, 205, 202, 93, 134, 100, 45, 183, 126, 204, 34, 132, 163, 72, 64, 131, 130, 110, 162, 231, 214, 178, 19, 107, 75, 242, 229, 105, 163, 238, 60, 219, 154, 96, 104, 227, 175, 114, 101, 109, 111, 118, 101, 100, 95, 101, 110, 116, 114, 105, 101, 115, 144]; Deserialize("missing field `index_value`")

11:42:09 [Tryorama - Local Conductor] debug: Jul 07 11:42:09.326 DEBUG wasm_trace: hc_zome_rea_agent_lib:zomes/rea_agent/lib/src/lib.rs:40 handle_create_agent::agent_type index Ok([Err(Wasm(Host("Wasm error while working with Ribosome: Deserialize([131, 172, 114, 101, 109, 111, 116, 101, 95, 101, 110, 116, 114, 121, 146, 196, 39, 132, 45, 36, 165, 79, 24, 69, 217, 175, 141, 113, 44, 168, 250, 251, 81, 126, 193, 104, 100, 34, 35, 111, 182, 71, 33, 99, 14, 80, 238, 191, 184, 209, 41, 174, 110, 124, 17, 238, 196, 39, 132, 33, 36, 17, 2, 67, 24, 128, 23, 194, 138, 161, 85, 167, 157, 219, 12, 75, 87, 39, 66, 172, 33, 22, 41, 83, 132, 215, 235, 12, 218, 173, 215, 135, 123, 94, 101, 230, 51, 174, 116, 97, 114, 103, 101, 116, 95, 101, 110, 116, 114, 105, 101, 115, 145, 146, 196, 39, 132, 45, 36, 165, 79, 24, 69, 217, 175, 141, 113, 44, 168, 250, 251, 81, 126, 193, 104, 100, 34, 35, 111, 182, 71, 33, 99, 14, 80, 238, 191, 184, 209, 41, 174, 110, 124, 17, 238, 196, 39, 132, 33, 36, 215, 205, 202, 93, 134, 100, 45, 183, 126, 204, 34, 132, 163, 72, 64, 131, 130, 110, 162, 231, 214, 178, 19, 107, 75, 242, 229, 105, 163, 238, 60, 219, 154, 96, 104, 227, 175, 114, 101, 109, 111, 118, 101, 100, 95, 101, 110, 116, 114, 105, 101, 115, 144])"))), Err(NotConfigured(ZomeName("agent"), FunctionName("")))])
```

key messages:
`Deserialize("missing field `index_value`")`
and
`Err(NotConfigured(ZomeName("agent"), FunctionName("")))`

It looks like the key name `index_value` changed on the StringLinkRequest type vs the RemoteLinkRequest type, from `source`.

**Comment by pospi** [comment]
hey, cool! This is the error I was expecting to be getting and confused as to why I wasn't. I think I just need to move a little more code away from the Agent-specific stuff and put it into the core libraries. And change some calling signature somewhere to line up that changed field.

**Comment by pospi** [comment]
@Connoropolous @weswalla should be good to merge now. If I do any more work to support `UnitId` in this branch I'll leave it local-only until I've confirmed the units readall test is working.

**Comment by pospi** [comment]
Units working now as well (:

**Review by Connoropolous — APPROVED** [review]
tests all passing locally and all the code looking good 👍 

these macros feel like superheros, they don't always make sense but they're mighty!

**Pull request merged**
