### PR TITLE
#219 -> Wire up REA Agent storage DNA

### LINKED ISSUE #219: Implement REA Agent
### MVP (simplest implementation)

- [x] Author a storage zome which allows any Holochain agent to store a blob of (`name` (string), `note` (string), `image` (string), `primaryLocation` (string), `type` (string)) and get back an `AgentAddress` pointing to this data. You can minimally create an `vf_attributes_hdk::AgentAddress` via `AgentAddress::new(dna_info()?.dna_hash, entry_hash)`
- [x] create `zome` `lib` and `storage` folders/crates under `rea_agent` and implement according to set patterns as can be seen in `rea_agreement` and elsewhere.
- [x] add those 3 crates into the top level Cargo.toml workspace definition
- [x] Wire it up to the query resolvers in `modules/vf-graphql-holochain/queries/agent.ts`
- [x] Implement a new agent mutation handler in `modules/vf-graphql-holochain/mutations/agent.ts` for `createPerson`
- [x] Include this zome in the DNA manifest in `happs/agent/dna.yaml`
- [x] Implement something separate for `Organization`, perhaps just a separate API endpoint which creates entries with a different "type" field. Wire this up to `createOrganization`.
- [x] #300
- [x] #311
- [x] #303 
- [x] #301 
- [x] #298

### PR DESCRIPTION
**Pull request by pospi**
Includes revising data storage architecture to deal with an extra layer of indirection wrapped around REA's `Agent`, such that `Organization`, `EcologicalAgent`, `Group` etc are representable; and that all agent types (including the singular `Person`) can be associated with custom metadata and storage for broadcasting profiles within the collaboration space.

To implement #219.

### CODE REVIEW

**Comment by weswalla** [comment]
@pospi noted about `AddressibleIdentifier`

**Comment by weswalla** [comment]
@Connoropolous @pospi create and update are working, but for some reason delete isn't. calling `delete_agent` spits out the following error: `"Could not convert entry to requested type\"`. I tried digging in to the functions and it seems like the error is coming from: https://github.com/h-REA/hREA/blob/9376f4ccccd71db1a94937e8f231748b6671404b/lib/hdk_records/src/entry_helpers.rs#L39 
but I'm not sure why there is an error when trying to convert from the serialized bytes to `EntryData`, as there don't seem to be any major differences from other `EntryData` types

**Comment by pospi** [comment]
You'll need to use `EntryStorage` with that, which is a wrapper struct containing the identifier info in addition to the `EntryData`. It's the difference between what actually gets stored in the DHT vs what is meaningfully "record data" within the application.

**Review by Connoropolous — APPROVED** [review]
This is great start. This is big enough that I am going to merge this, and clearly map and track the remaining scopes of work for this

**Pull request merged**
